### ISSUE TITLE
mp4 upload progress bar not working

### ISSUE THREAD

**Issue by kalanavw** [vasuskimo/Skimo_Newton_Issues#49]
**Its is better to add progress bar or any loading mechanism otherwise user may be confused**

![Capture1](https://user-images.githubusercontent.com/29678040/80625750-46ab8100-8a6b-11ea-9bd5-04c8b1e7550a.JPG)

**Comment by vasuskimo** [comment]
Duplicate of https://github.com/vasuskimo/Skimo_Newton_Issues/issues/45
