### ISSUE TITLE
Grammatical issue on landing page

### ISSUE THREAD

**Issue by SamhitaVasu** [vasuskimo/Skimo_Newton_Issues#8]
Remove the two commas before "that" and "to" in the sentence "Skimo Engine is a video summarization and indexing engine, that uses machine learning/computer vision and video processing algorithms,to automatically detect points of interest based on the genre of the video,regardless of the language." Also add a space before "regardless."
Alternative: change sentence to "Skimo Engine is a video summarization and indexing engine, which uses machine learning/computer vision and video processing algorithms to automatically detect points of interest based on the genre of the video, regardless of the language."
Also, unsure whether it should be "Skimo Engine is..." or "The Skimo Engine is..."
Page of issue: http://198.74.50.75/meetings.html

**Comment by vasuskimo** [comment]
Fixed it.
